apiVersion: apps/v1
kind: Deployment
metadata:
  name: educationalapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: educationalapp
  template:
    metadata:
      labels:
        app: educationalapp
    spec:
      containers:
      - name: educationalapp
        image: srinivasarao2468/educationalapp:v1
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: educationalapp
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: educationalapp
              key: password
        - name: HOST
          value: mongodb.default.svc.cluster.local
        - name: PORT
          value: "27017"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: educationalapp
spec:
  type: NodePort
  selector:
    app: educationalapp
  ports:
  - port: 4000
    targetPort: 4000
